name: hands-env
dependencies:
  - python=3.6
  - numpy=1.12
  - opencv=3.1.0
  - scikit-image=0.13.0
  - scikit-learn=0.19.0
  - scipy=0.19.0
  - pandas=0.20.3
  - matplotlib=2.0.2
  - xlrd=1.0.0
  - qt=5.6.0
  - ipython=5.1.0
  - ipython_genutils=0.1.0
  - ipywidgets=5.2.2
  - itsdangerous=0.24
  - seaborn=0.8
  - jupyter=1.0.0
  - jupyter_client=4.4.0
  - jupyter_console=5.0.0
  - jupyter_core=4.2
#  - nb_conda=2.2.0
